import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, Inter, Space_Grotesk, Fredoka, Nunito } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import UserProfileButton from "@/components/user/UserProfileButton";
import { ThemeProvider } from "next-themes";
import LobbyChat from "@/components/lobby/LobbyChat";
import ThemedToaster from "@/components/themed-toaster";
import { Suspense } from "react";
import { WebSocketProvider } from "@/hooks/websocketcontext";
import { UserProvider } from "@/hooks/usercontext";
import { LobbyContextProvider } from "@/hooks/lobbycontext";
import { Background } from "@/components/background/background";

const fredoka = Fredoka({
  subsets: ["latin"],
  variable: "--font-fredoka",
  weight: ["400", "500", "600", "700"],
});

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["400", "600", "700", "800", "900"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

const geistHeading = Geist({ subsets: ["latin"], variable: "--font-heading" });

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OrdioArena",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", figtree.variable, geistHeading.variable, inter.variable, spaceGrotesk.variable, fredoka.variable, nunito.variable)}>
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <WebSocketProvider>
            <UserProvider>
              <LobbyContextProvider>
                <TooltipProvider>
                  {children}
                  <Suspense fallback={null}>
                    <LobbyChat />
                  </Suspense>
                  <UserProfileButton />
                </TooltipProvider>
              </LobbyContextProvider>
            </UserProvider>
          </WebSocketProvider>
          <ThemedToaster />
        </ThemeProvider>
        <Background />
      </body>
    </html>
  );
}
